targets:
  $default:
    builders:
      slang_build_runner:
        options:
          namespaces: true
          input_directory: assets/i18n
          output_directory: lib
          output_file_name: translations.g.dart
          imports:
            - package:limer_music_enquirer/db/settings/metadata_order/ap_song.dart
          contexts:
            ApSongMetadataType:
              generate_enum: false
              default_parameter: type
              paths:
                - assets/i18n/metadata.i18n.json
                - assets/i18n/metadata_ja.i18n.json
              enum:
                - albumName
                - artistName
                - attribution
                - audioVariants
                - composerName
                - contentRating
                - discNumber
                - durationInMillis
                - genreNames
                - hasLyrics
                - isAppleDigitalMaster
                - isrc
                - movementCount
                - movementName
                - movementNumber
                - name
                - releaseDate
                - trackNumber
                - workName
      slang_i18n_generator:
        options:
          additional_locales:
            - ja