name: songs_inspector
description: Inspect the information of current playing song.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.0
  flutter_hooks: ^0.18.6
  go_router: ^6.0.10
  hooks_riverpod: ^2.2.0
  riverpod_annotation: ^1.2.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.1.1
  riverpod_generator: ^1.2.0

flutter:
  uses-material-design: true