name: limer_music_enquirer
description: A Flutter App for looking into music information.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dart_jsonwebtoken: ^2.7.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.0
  flutter_hooks: ^0.18.6
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0
  go_router: ^6.0.10
  hooks_riverpod: ^2.2.0
  json_annotation: ^4.8.0
  logging: ^1.1.1
  retrofit: ^4.0.1
  riverpod_annotation: ^1.2.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  go_router_builder: ^1.1.1
  json_serializable: ^6.6.1
  retrofit_generator: ^5.0.0
  riverpod_generator: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - auth/apple_music/auth_key.p8
    - auth/apple_music/key_id
    - auth/apple_music/team_id