name: limer_music_enquirer
description: A Flutter App for looking into music information.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  beamer: ^1.5.3
  cupertino_icons: ^1.0.2
  dart_jsonwebtoken: ^2.7.1
  dio: ^5.0.0
  flex_seed_scheme: ^1.2.2
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.0
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  go_router: ^6.0.10
  hooks_riverpod: ^2.2.0
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  logging: ^1.1.1
  path_provider: ^2.0.14
  riverpod_annotation: ^2.0.0
  slang: ^3.15.1
  slang_flutter: ^3.15.0
  udy_flutter_layout:
    git: 
      url: https://github.com/kosuke-udy/udy_flutter_layout.git

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  isar_generator: ^3.0.5
  pigeon: ^9.0.1
  riverpod_generator: ^2.1.6
  slang_build_runner: ^3.15.0
  slang_i18n_generator:
    git: 
      url: https://github.com/kosuke-udy/slang_i18n_generator.git

flutter:
  uses-material-design: true
  assets:
    - assets/limer_logo.png
    - auth/apple_music/auth_key.p8
    - auth/apple_music/key_id
    - auth/apple_music/team_id
    - auth/apple_music/mock_dev_token
    - auth/apple_music/mock_user_token