import 'am_native_api.pigeon.dart';
import 'enums/am_user_auth_status.dart';

// The Wrapper of Native API generated by pigeon
// iOS: StoreKit
class AmNativeApiWrapper {
  static final _instance = AmNativeApiWrapper._internal();
  final _nativeApi = AmNativeApi();

  factory AmNativeApiWrapper() {
    return _instance;
  }

  AmNativeApiWrapper._internal();

  Future<AmUserAuthStatus> getUserAuthStatus() async {
    final result =
        AmUserAuthStatus.fromString(await _nativeApi.getUserAuthStatus());
    return result;
  }

  Future<AmUserAuthStatus> requestUserAuth() async {
    final result =
        AmUserAuthStatus.fromString(await _nativeApi.requestUserAuth());
    return result;
  }

  Future<String> requestUserToken(String devToken) async {
    return await _nativeApi.requestUserToken(devToken);
  }
}
